# 如果 2.5m 内有障碍物，则把障碍物添加到 costmap
obstacle_range: 2.5

# 如果 3m 内没有障碍物，则清除 costmap 该方向上的障碍物
raytrace_range: 3.0

# 机器人碰撞尺寸（半径）
robot_radius: 0.2

# 障碍物膨胀半径
inflation_radius: 0.3

# costmap 数据的来源
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}
