local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0

  # 地图位置跟随机器人移动
  rolling_window: true

  # 局部 costmap 的尺寸
  width: 6.0
  height: 6.0
  
  static_map: false